---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nginx
  namespace: house
provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-local-https-volume
  namespace: house
  labels:
    directory: https
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-nginx
  local:
    path: /data/nginx/https
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k-cup

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-local-https-claim
  namespace: house
spec:
  storageClassName: local-nginx
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: https


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: house
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: nginx
    spec:
      containers:
      - name: nginx
        image:  nginx:1.16.0-alpine
        imagePullPolicy: Always

        volumeMounts:
          - name: nginx-local-https-volume
            mountPath: "/etc/letsencrypt/live"
          - name: nginx-config-volume
            mountPath: "/etc/nginx/nginx.conf"
            

      volumes:
      - name: nginx-local-https-volume
        persistentVolumeClaim:
          claimName: nginx-local-https-claim
      - name: nginx-config-volume
        hostPath:
          path: /data/nginx/nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: house
spec:
  selector:
    app: nginx
  ports:
  - port: 3999
    targetPort: 80
    name: nginx-http-tcp
    protocol: TCP
  - port: 4000
    targetPort: 443
    name: nginx-https-tcp
    protocol: TCP
  externalIPs:
  - 192.168.0.249